"""Create initial todos table

Revision ID: 88247819406e
Revises: 
Create Date: 2020-07-02 04:49:35.328492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88247819406e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
